processors:
- add_cloud_metadata: ~

heartbeat.config.monitors:
  path: /opt/heartbeat/monitors.d/*.yml
  reload.enabled: true
  reload.period: 15s

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["${OUTPUT_ELASTICSEARCH_HOSTS}"]

  # Protocol - either `http` (default) or `https`.
  protocol: "https"
  
  # Authentication credentials - either API key or username/password.
  api_key: "${OUTPUT_ELASTICSEARCH_API_KEY}"
  ssl.verification_mode: none
